In [7]:
import pandas as pd
import numpy as np

import seaborn as sns

df = sns.load_dataset("titanic")

# Performing first look ritual

df.head()
df.info()
df.describe()
df.dtypes

df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [8]:
# Counting missing columns

count = df.isnull().sum()
print(count)

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [9]:
# Handeling Missing Values

## dropping: class, alive, who, embarked (repeating columns)
df = df.drop(columns=['class', 'alive', 'who', 'embarked'])

## filling: age, deck, embark_town
df['age'] = df['age'].fillna(df['age'].median())
df['deck'] = df['deck'].cat.add_categories('Unknown').fillna('Unknown')
df['embark_town'] = df['embark_town'].fillna('Unknown')

handled_count = df.isnull().sum()
print(handled_count)

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
adult_male     0
deck           0
embark_town    0
alone          0
dtype: int64

In [15]:
# Checking datatypes after handling missing values

df.dtypes

survived          int64
pclass            int64
sex              object
age             float64
sibsp             int64
parch             int64
fare            float64
adult_male         bool
deck           category
embark_town      object
alone              bool
dtype: object

In [16]:
# Encoding Text Values

df = pd.get_dummies(df, columns=['sex', 'embark_town', 'deck'], drop_first=True)

df

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,sex_male,embark_town_Queenstown,embark_town_Southampton,embark_town_Unknown,deck_B,deck_C,deck_D,deck_E,deck_F,deck_G,deck_Unknown
0,0,3,22.0,1,0,7.2500,True,False,True,False,True,False,False,False,False,False,False,False,True
1,1,1,38.0,1,0,71.2833,False,False,False,False,False,False,False,True,False,False,False,False,False
2,1,3,26.0,0,0,7.9250,False,True,False,False,True,False,False,False,False,False,False,False,True
3,1,1,35.0,1,0,53.1000,False,False,False,False,True,False,False,True,False,False,False,False,False
4,0,3,35.0,0,0,8.0500,True,True,True,False,True,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,13.0000,True,True,True,False,True,False,False,False,False,False,False,False,True
887,1,1,19.0,0,0,30.0000,False,True,False,False,True,False,True,False,False,False,False,False,False
888,0,3,28.0,1,2,23.4500,False,False,False,False,True,False,False,False,False,False,False,False,True
889,1,1,26.0,0,0,30.0000,True,True,True,False,False,False,False,True,False,False,False,False,False
890,0,3,32.0,0,0,7.7500,True,True,True,True,False,False,False,False,False,False,False,False,True

In [17]:
# Scaling

from sklearn.preprocessing import StandardScaler

features = df.drop(columns=['survived'])
target = df['survived']
scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

print(scaled_features)

[[ 0.82737724 -0.56573646  0.43279337 ... -0.12168146 -0.06715343
   0.54319254]
 [-1.56610693  0.66386103  0.43279337 ... -0.12168146 -0.06715343
  -1.84096783]
 [ 0.82737724 -0.25833709 -0.4745452  ... -0.12168146 -0.06715343
   0.54319254]
 ...
 [ 0.82737724 -0.1046374   0.43279337 ... -0.12168146 -0.06715343
   0.54319254]
 [-1.56610693 -0.25833709 -0.4745452  ... -0.12168146 -0.06715343
  -1.84096783]
 [ 0.82737724  0.20276197 -0.4745452  ... -0.12168146 -0.06715343
   0.54319254]]

In [18]:
# Spliting into train/test

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(scaled_features, target, test_size=0.2, random_state=42)

print('Trained Rows: ', len(x_train))
print('Tested Rows: ', len(x_test))

Trained Rows:  712
Tested Rows:  179