In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'age': [25, 32, np.nan, 45, 51],
    'city': ['Islamabad', 'Karachi', 'Rawalpindi', 'Taxila', 'Murree'],
    'income': [45000, 540000, 610000, np.nan, 890000],
    'bought': [0,1,1,1,0]
})

df

    age        city    income  bought
0  25.0   Islamabad   45000.0       0
1  32.0     Karachi  540000.0       1
2   NaN  Rawalpindi  610000.0       1
3  45.0      Taxila       NaN       1
4  51.0      Murree  890000.0       0

In [3]:
# Problem 1: Missing Values ## df.dropna (to delete rows)

print(df.isnull().sum())

df['age'] = df['age'].fillna(df['age'].median())
df['income'] = df['income'].fillna(df['income'].median())

print()

print(df.isnull().sum())
df

age       1
city      0
income    1
bought    0
dtype: int64

age       0
city      0
income    0
bought    0
dtype: int64

    age        city    income  bought
0  25.0   Islamabad   45000.0       0
1  32.0     Karachi  540000.0       1
2  38.5  Rawalpindi  610000.0       1
3  45.0      Taxila  575000.0       1
4  51.0      Murree  890000.0       0

In [9]:
# Problem 2: Encoding Text Values

df = pd.get_dummies(df, columns = ['city'], drop_first = True)

df

,age,income,bought,city_Karachi,city_Murree,city_Rawalpindi,city_Taxila
0,25.0,45000.0,0,False,False,False,False
1,32.0,540000.0,1,True,False,False,False
2,38.5,610000.0,1,False,False,True,False
3,45.0,575000.0,1,False,False,False,True
4,51.0,890000.0,0,False,True,False,False

In [12]:
# Problem 3: Scaling

from sklearn.preprocessing import StandardScaler

features = df.drop(columns='bought')
target = df['bought']

scaler = StandardScaler()

scaled_features = scaler.fit_transform(features)

print(scaled_features)

[[-1.44633586 -1.78224546 -0.5        -0.5        -0.5        -0.5       ]
 [-0.68510646  0.02927713  2.         -0.5        -0.5        -0.5       ]
 [ 0.02174941  0.28545205 -0.5        -0.5         2.         -0.5       ]
 [ 0.72860528  0.15736459 -0.5        -0.5        -0.5         2.        ]
 [ 1.38108762  1.3101517  -0.5         2.         -0.5        -0.5       ]]

In [13]:
# Problem 4: Spliting

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

print('Training Rows:', len(x_train))
print('Testing Rows:', len(x_test))

Training Rows: 4
Testing Rows: 1