In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns

df = sns.load_dataset("diamonds")

# Performing First Look Ritual

df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 10 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carat    53940 non-null  float64
 1   cut      53940 non-null  category
 2   color    53940 non-null  category
 3   clarity  53940 non-null  category
 4   depth    53940 non-null  float64
 5   table    53940 non-null  float64
 6   price    53940 non-null  int64
 7   x        53940 non-null  float64
 8   y        53940 non-null  float64
 9   z        53940 non-null  float64
dtypes: category(3), float64(6), int64(1)
memory usage: 3.0 MB

,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [ ]:
# Checking how many rows have missing values

count = df.isnull().sum()
print(count)
df

carat      0
cut        0
color      0
clarity    0
depth      0
table      0
price      0
x          0
y          0
z          0
dtype: int64

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [ ]:
# Checking Data types

df.dtypes

carat       float64
cut        category
color      category
clarity    category
depth       float64
table       float64
price         int64
x           float64
y           float64
z           float64
dtype: object

In [ ]:
# Encoding Text Columns

df = pd.get_dummies(df, columns=['cut', 'color', 'clarity'])
df

,carat,depth,table,price,x,y,z,cut_Ideal,cut_Premium,cut_Very Good,...,color_I,color_J,clarity_IF,clarity_VVS1,clarity_VVS2,clarity_VS1,clarity_VS2,clarity_SI1,clarity_SI2,clarity_I1
0,0.23,61.5,55.0,326,3.95,3.98,2.43,True,False,False,...,False,False,False,False,False,False,False,False,True,False
1,0.21,59.8,61.0,326,3.89,3.84,2.31,False,True,False,...,False,False,False,False,False,False,False,True,False,False
2,0.23,56.9,65.0,327,4.05,4.07,2.31,False,False,False,...,False,False,False,False,False,True,False,False,False,False
3,0.29,62.4,58.0,334,4.20,4.23,2.63,False,True,False,...,True,False,False,False,False,False,True,False,False,False
4,0.31,63.3,58.0,335,4.34,4.35,2.75,False,False,False,...,False,True,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53935,0.72,60.8,57.0,2757,5.75,5.76,3.50,True,False,False,...,False,False,False,False,False,False,False,True,False,False
53936,0.72,63.1,55.0,2757,5.69,5.75,3.61,False,False,False,...,False,False,False,False,False,False,False,True,False,False
53937,0.70,62.8,60.0,2757,5.66,5.68,3.56,False,False,True,...,False,False,False,False,False,False,False,True,False,False
53938,0.86,61.0,58.0,2757,6.15,6.12,3.74,False,True,False,...,False,False,False,False,False,False,False,False,True,False
53939,0.75,62.2,55.0,2757,5.83,5.87,3.64,True,False,False,...,False,False,False,False,False,False,False,False,True,False

In [ ]:
# Train/Test Split

from sklearn.model_selection import train_test_split

x = df.drop(columns=["price"])
y = df["price"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print('Trained Rows: ', len(x_train))
print('Tested Rows: ', len(x_test))

Trained Rows:  43152
Tested Rows:  10788

In [ ]:
# Predicting

from sklearn.linear_model import LinearRegression

lin = LinearRegression()
lin.fit(x_train, y_train)
lin.preds = lin.predict(x_test)

In [ ]:
# Linear Regression

from sklearn.metrics import mean_squared_error, root_mean_squared_error, r2_score

print('Linear Regression:-')
print(f'MSE: {mean_squared_error(y_test, lin.preds)}')
print(f'RMSE: {root_mean_squared_error(y_test, lin.preds)}')
print(f'R2: {r2_score(y_test, lin.preds)}')

Linear Regression:-
MSE: 1288705.477851674
RMSE: 1135.2116445190622
R2: 0.9189331350419387

In [ ]:
# Random Forest

from sklearn.ensemble import RandomForestRegressor

forest = RandomForestRegressor(n_estimators=100, random_state=42)
forest.fit(x_train, y_train)
forest.preds = forest.predict(x_test)

print('Random Forest:-')
print(f'MSE: {mean_squared_error(y_test, forest.preds)}')
print(f'RMSE: {root_mean_squared_error(y_test, forest.preds)}')
print(f'R2: {r2_score(y_test, forest.preds)}')

Random Forest:-
MSE: 300804.2684697664
RMSE: 548.4562593951923
R2: 0.9810777098181517

In [ ]:
# Important Features

importances = pd.Series(forest.feature_importances_, index=x.columns)
print(importances.sort_values(ascending=False))

carat            0.613378
y                0.272758
clarity_SI2      0.019434
clarity_I1       0.015002
clarity_SI1      0.014461
color_J          0.010315
color_I          0.007274
clarity_VS2      0.007093
color_H          0.005647
clarity_VS1      0.005627
x                0.005541
z                0.005214
depth            0.003222
color_D          0.002839
color_G          0.002597
table            0.002191
color_E          0.001637
color_F          0.001426
clarity_VVS2     0.001116
cut_Ideal        0.001002
clarity_IF       0.000698
clarity_VVS1     0.000491
cut_Premium      0.000359
cut_Very Good    0.000284
cut_Good         0.000246
cut_Fair         0.000148
dtype: float64

In [ ]:
# Which model wins, and what's the top feature?

print(f'Which model wins: Random Forest')
print(f'Top Feature: carat')

Which model wins: Random Forest
Top Feature: carat